// Minecraft item ID to display name + emoji
export const ITEM_NAMES: Record<string, { name: string; emoji: string; color?: string }> = {
  // Tools
  "minecraft:wooden_sword": { name: "Wooden Sword", emoji: "🗡️", color: "#9C7A3C" },
  "minecraft:stone_sword": { name: "Stone Sword", emoji: "🗡️", color: "#8A8A8A" },
  "minecraft:iron_sword": { name: "Iron Sword", emoji: "🗡️", color: "#D3C4B4" },
  "minecraft:golden_sword": { name: "Gold Sword", emoji: "🗡️", color: "#FAEE4D" },
  "minecraft:diamond_sword": { name: "Diamond Sword", emoji: "🗡️", color: "#5ECFCF" },
  "minecraft:netherite_sword": { name: "Netherite Sword", emoji: "🗡️", color: "#4B4046" },
  "minecraft:wooden_pickaxe": { name: "Wooden Pickaxe", emoji: "⛏️", color: "#9C7A3C" },
  "minecraft:stone_pickaxe": { name: "Stone Pickaxe", emoji: "⛏️", color: "#8A8A8A" },
  "minecraft:iron_pickaxe": { name: "Iron Pickaxe", emoji: "⛏️", color: "#D3C4B4" },
  "minecraft:golden_pickaxe": { name: "Gold Pickaxe", emoji: "⛏️", color: "#FAEE4D" },
  "minecraft:diamond_pickaxe": { name: "Diamond Pickaxe", emoji: "⛏️", color: "#5ECFCF" },
  "minecraft:netherite_pickaxe": { name: "Netherite Pickaxe", emoji: "⛏️", color: "#4B4046" },
  "minecraft:wooden_axe": { name: "Wooden Axe", emoji: "🪓", color: "#9C7A3C" },
  "minecraft:stone_axe": { name: "Stone Axe", emoji: "🪓", color: "#8A8A8A" },
  "minecraft:iron_axe": { name: "Iron Axe", emoji: "🪓", color: "#D3C4B4" },
  "minecraft:golden_axe": { name: "Gold Axe", emoji: "🪓", color: "#FAEE4D" },
  "minecraft:diamond_axe": { name: "Diamond Axe", emoji: "🪓", color: "#5ECFCF" },
  "minecraft:netherite_axe": { name: "Netherite Axe", emoji: "🪓", color: "#4B4046" },
  "minecraft:wooden_shovel": { name: "Wooden Shovel", emoji: "🪚", color: "#9C7A3C" },
  "minecraft:stone_shovel": { name: "Stone Shovel", emoji: "🪚", color: "#8A8A8A" },
  "minecraft:iron_shovel": { name: "Iron Shovel", emoji: "🪚", color: "#D3C4B4" },
  "minecraft:golden_shovel": { name: "Gold Shovel", emoji: "🪚", color: "#FAEE4D" },
  "minecraft:diamond_shovel": { name: "Diamond Shovel", emoji: "🪚", color: "#5ECFCF" },
  "minecraft:netherite_shovel": { name: "Netherite Shovel", emoji: "🪚", color: "#4B4046" },
  "minecraft:wooden_hoe": { name: "Wooden Hoe", emoji: "🌾", color: "#9C7A3C" },
  "minecraft:stone_hoe": { name: "Stone Hoe", emoji: "🌾", color: "#8A8A8A" },
  "minecraft:iron_hoe": { name: "Iron Hoe", emoji: "🌾", color: "#D3C4B4" },
  "minecraft:golden_hoe": { name: "Gold Hoe", emoji: "🌾", color: "#FAEE4D" },
  "minecraft:diamond_hoe": { name: "Diamond Hoe", emoji: "🌾", color: "#5ECFCF" },
  "minecraft:netherite_hoe": { name: "Netherite Hoe", emoji: "🌾", color: "#4B4046" },

  // Armor
  "minecraft:leather_helmet": { name: "Leather Helmet", emoji: "🪖", color: "#8B5E3C" },
  "minecraft:chainmail_helmet": { name: "Chainmail Helmet", emoji: "🪖", color: "#9E9E9E" },
  "minecraft:iron_helmet": { name: "Iron Helmet", emoji: "🪖", color: "#D3C4B4" },
  "minecraft:golden_helmet": { name: "Gold Helmet", emoji: "🪖", color: "#FAEE4D" },
  "minecraft:diamond_helmet": { name: "Diamond Helmet", emoji: "🪖", color: "#5ECFCF" },
  "minecraft:netherite_helmet": { name: "Netherite Helmet", emoji: "🪖", color: "#4B4046" },
  "minecraft:leather_chestplate": { name: "Leather Chestplate", emoji: "🛡️", color: "#8B5E3C" },
  "minecraft:chainmail_chestplate": { name: "Chainmail Chestplate", emoji: "🛡️", color: "#9E9E9E" },
  "minecraft:iron_chestplate": { name: "Iron Chestplate", emoji: "🛡️", color: "#D3C4B4" },
  "minecraft:golden_chestplate": { name: "Gold Chestplate", emoji: "🛡️", color: "#FAEE4D" },
  "minecraft:diamond_chestplate": { name: "Diamond Chestplate", emoji: "🛡️", color: "#5ECFCF" },
  "minecraft:netherite_chestplate": { name: "Netherite Chestplate", emoji: "🛡️", color: "#4B4046" },
  "minecraft:leather_leggings": { name: "Leather Leggings", emoji: "👖", color: "#8B5E3C" },
  "minecraft:chainmail_leggings": { name: "Chainmail Leggings", emoji: "👖", color: "#9E9E9E" },
  "minecraft:iron_leggings": { name: "Iron Leggings", emoji: "👖", color: "#D3C4B4" },
  "minecraft:golden_leggings": { name: "Gold Leggings", emoji: "👖", color: "#FAEE4D" },
  "minecraft:diamond_leggings": { name: "Diamond Leggings", emoji: "👖", color: "#5ECFCF" },
  "minecraft:netherite_leggings": { name: "Netherite Leggings", emoji: "👖", color: "#4B4046" },
  "minecraft:leather_boots": { name: "Leather Boots", emoji: "👢", color: "#8B5E3C" },
  "minecraft:chainmail_boots": { name: "Chainmail Boots", emoji: "👢", color: "#9E9E9E" },
  "minecraft:iron_boots": { name: "Iron Boots", emoji: "👢", color: "#D3C4B4" },
  "minecraft:golden_boots": { name: "Gold Boots", emoji: "👢", color: "#FAEE4D" },
  "minecraft:diamond_boots": { name: "Diamond Boots", emoji: "👢", color: "#5ECFCF" },
  "minecraft:netherite_boots": { name: "Netherite Boots", emoji: "👢", color: "#4B4046" },
  "minecraft:elytra": { name: "Elytra", emoji: "🪽", color: "#a0c4ff" },

  // Food
  "minecraft:apple": { name: "Apple", emoji: "🍎", color: "#E32A2A" },
  "minecraft:golden_apple": { name: "Golden Apple", emoji: "🍎", color: "#FAEE4D" },
  "minecraft:enchanted_golden_apple": { name: "Enchanted Golden Apple", emoji: "🍎", color: "#FF55FF" },
  "minecraft:bread": { name: "Bread", emoji: "🍞", color: "#9C7A3C" },
  "minecraft:cooked_beef": { name: "Steak", emoji: "🥩", color: "#8B0000" },
  "minecraft:beef": { name: "Raw Beef", emoji: "🥩", color: "#C24040" },
  "minecraft:cooked_chicken": { name: "Cooked Chicken", emoji: "🍗", color: "#DAA520" },
  "minecraft:chicken": { name: "Raw Chicken", emoji: "🍗", color: "#FFA07A" },
  "minecraft:cooked_porkchop": { name: "Cooked Porkchop", emoji: "🥓", color: "#CD853F" },
  "minecraft:porkchop": { name: "Raw Porkchop", emoji: "🥓", color: "#FFA0A0" },
  "minecraft:cooked_salmon": { name: "Cooked Salmon", emoji: "🐟", color: "#FA8072" },
  "minecraft:salmon": { name: "Raw Salmon", emoji: "🐟", color: "#FF7F7F" },
  "minecraft:cooked_cod": { name: "Cooked Cod", emoji: "🐠", color: "#DEB887" },
  "minecraft:cod": { name: "Raw Cod", emoji: "🐠", color: "#F5DEB3" },
  "minecraft:carrot": { name: "Carrot", emoji: "🥕", color: "#FF7700" },
  "minecraft:golden_carrot": { name: "Golden Carrot", emoji: "🥕", color: "#FAEE4D" },
  "minecraft:potato": { name: "Potato", emoji: "🥔", color: "#DEB887" },
  "minecraft:baked_potato": { name: "Baked Potato", emoji: "🥔", color: "#A0522D" },
  "minecraft:melon_slice": { name: "Melon Slice", emoji: "🍉", color: "#FF4444" },
  "minecraft:mushroom_stew": { name: "Mushroom Stew", emoji: "🍲", color: "#8B4513" },
  "minecraft:rabbit_stew": { name: "Rabbit Stew", emoji: "🍲", color: "#DEB887" },
  "minecraft:beetroot_soup": { name: "Beetroot Soup", emoji: "🍲", color: "#8B0036" },
  "minecraft:cake": { name: "Cake", emoji: "🎂", color: "#FFFFFF" },
  "minecraft:cookie": { name: "Cookie", emoji: "🍪", color: "#8B4513" },
  "minecraft:honey_bottle": { name: "Honey Bottle", emoji: "🍯", color: "#FFA500" },
  "minecraft:glow_berries": { name: "Glow Berries", emoji: "🫐", color: "#FFA500" },
  "minecraft:sweet_berries": { name: "Sweet Berries", emoji: "🍇", color: "#8B0036" },

  // Resources
  "minecraft:diamond": { name: "Diamond", emoji: "💎", color: "#5ECFCF" },
  "minecraft:emerald": { name: "Emerald", emoji: "💚", color: "#17DD62" },
  "minecraft:gold_ingot": { name: "Gold Ingot", emoji: "🏅", color: "#FAEE4D" },
  "minecraft:iron_ingot": { name: "Iron Ingot", emoji: "🔩", color: "#D3C4B4" },
  "minecraft:netherite_ingot": { name: "Netherite Ingot", emoji: "⬛", color: "#4B4046" },
  "minecraft:coal": { name: "Coal", emoji: "🪨", color: "#333333" },
  "minecraft:charcoal": { name: "Charcoal", emoji: "🪨", color: "#4A4A4A" },
  "minecraft:redstone": { name: "Redstone", emoji: "🔴", color: "#E32A2A" },
  "minecraft:lapis_lazuli": { name: "Lapis Lazuli", emoji: "🔵", color: "#1B4FAF" },
  "minecraft:quartz": { name: "Nether Quartz", emoji: "🔷", color: "#EAE4D5" },
  "minecraft:amethyst_shard": { name: "Amethyst Shard", emoji: "🔮", color: "#9B59B6" },
  "minecraft:copper_ingot": { name: "Copper Ingot", emoji: "🪙", color: "#b87333" },

  // Blocks
  "minecraft:dirt": { name: "Dirt", emoji: "🟫", color: "#866043" },
  "minecraft:grass_block": { name: "Grass Block", emoji: "🌿", color: "#5D8A3C" },
  "minecraft:stone": { name: "Stone", emoji: "🪨", color: "#8A8A8A" },
  "minecraft:cobblestone": { name: "Cobblestone", emoji: "🪨", color: "#707070" },
  "minecraft:sand": { name: "Sand", emoji: "🏖️", color: "#F5E07B" },
  "minecraft:gravel": { name: "Gravel", emoji: "⬛", color: "#7F7F7F" },
  "minecraft:wood": { name: "Wood Log", emoji: "🪵", color: "#9C7A3C" },
  "minecraft:oak_log": { name: "Oak Log", emoji: "🪵", color: "#9C7A3C" },
  "minecraft:birch_log": { name: "Birch Log", emoji: "🪵", color: "#C8C8C8" },
  "minecraft:spruce_log": { name: "Spruce Log", emoji: "🪵", color: "#6B4B2A" },
  "minecraft:jungle_log": { name: "Jungle Log", emoji: "🪵", color: "#5B4B2A" },
  "minecraft:acacia_log": { name: "Acacia Log", emoji: "🪵", color: "#A0522D" },
  "minecraft:dark_oak_log": { name: "Dark Oak Log", emoji: "🪵", color: "#4A3728" },
  "minecraft:torch": { name: "Torch", emoji: "🔦", color: "#FFA500" },
  "minecraft:chest": { name: "Chest", emoji: "📦", color: "#9C7A3C" },
  "minecraft:crafting_table": { name: "Crafting Table", emoji: "🔨", color: "#9C7A3C" },
  "minecraft:furnace": { name: "Furnace", emoji: "🔥", color: "#8A8A8A" },
  "minecraft:bookshelf": { name: "Bookshelf", emoji: "📚", color: "#9C7A3C" },
  "minecraft:obsidian": { name: "Obsidian", emoji: "⬛", color: "#1A0A2E" },
  "minecraft:glass": { name: "Glass", emoji: "🪟", color: "#A8D8EA" },
  "minecraft:tnt": { name: "TNT", emoji: "💥", color: "#E32A2A" },
  "minecraft:glowstone": { name: "Glowstone", emoji: "✨", color: "#FFDD77" },
  "minecraft:netherrack": { name: "Netherrack", emoji: "🔴", color: "#8B2222" },
  "minecraft:soul_sand": { name: "Soul Sand", emoji: "😱", color: "#5A4234" },
  "minecraft:end_stone": { name: "End Stone", emoji: "🟡", color: "#E5E0A0" },

  // Special items
  "minecraft:bow": { name: "Bow", emoji: "🏹", color: "#9C7A3C" },
  "minecraft:crossbow": { name: "Crossbow", emoji: "🏹", color: "#9C7A3C" },
  "minecraft:arrow": { name: "Arrow", emoji: "➡️", color: "#A0A0A0" },
  "minecraft:spectral_arrow": { name: "Spectral Arrow", emoji: "➡️", color: "#FFFF77" },
  "minecraft:fishing_rod": { name: "Fishing Rod", emoji: "🎣", color: "#9C7A3C" },
  "minecraft:flint_and_steel": { name: "Flint & Steel", emoji: "🔥", color: "#8A8A8A" },
  "minecraft:bucket": { name: "Bucket", emoji: "🪣", color: "#D3C4B4" },
  "minecraft:water_bucket": { name: "Water Bucket", emoji: "🪣", color: "#4455FF" },
  "minecraft:lava_bucket": { name: "Lava Bucket", emoji: "🪣", color: "#FF4400" },
  "minecraft:milk_bucket": { name: "Milk Bucket", emoji: "🥛", color: "#FFFFFF" },
  "minecraft:potion": { name: "Potion", emoji: "🧪", color: "#8855FF" },
  "minecraft:splash_potion": { name: "Splash Potion", emoji: "🧪", color: "#AA66FF" },
  "minecraft:lingering_potion": { name: "Lingering Potion", emoji: "🧪", color: "#CC88FF" },
  "minecraft:ender_pearl": { name: "Ender Pearl", emoji: "🔮", color: "#145A14" },
  "minecraft:eye_of_ender": { name: "Eye of Ender", emoji: "👁️", color: "#00CC88" },
  "minecraft:blaze_rod": { name: "Blaze Rod", emoji: "🔥", color: "#FFAA00" },
  "minecraft:nether_star": { name: "Nether Star", emoji: "⭐", color: "#FFFFFF" },
  "minecraft:beacon": { name: "Beacon", emoji: "🌟", color: "#88FFFF" },
  "minecraft:totem_of_undying": { name: "Totem of Undying", emoji: "🗿", color: "#FFAA00" },
  "minecraft:shield": { name: "Shield", emoji: "🛡️", color: "#8B6914" },
  "minecraft:trident": { name: "Trident", emoji: "🔱", color: "#5ECFCF" },
  "minecraft:compass": { name: "Compass", emoji: "🧭", color: "#D3C4B4" },
  "minecraft:clock": { name: "Clock", emoji: "🕐", color: "#FAEE4D" },
  "minecraft:map": { name: "Map", emoji: "🗺️", color: "#C8A060" },
  "minecraft:book": { name: "Book", emoji: "📖", color: "#C8A060" },
  "minecraft:written_book": { name: "Written Book", emoji: "📘", color: "#4A6FA5" },
  "minecraft:enchanted_book": { name: "Enchanted Book", emoji: "📕", color: "#AA44FF" },
  "minecraft:name_tag": { name: "Name Tag", emoji: "🏷️", color: "#FF8888" },
  "minecraft:lead": { name: "Lead", emoji: "🔗", color: "#9C7A3C" },
  "minecraft:saddle": { name: "Saddle", emoji: "🐴", color: "#8B5E3C" },
  "minecraft:stick": { name: "Stick", emoji: "🪵", color: "#9C7A3C" },
  "minecraft:string": { name: "String", emoji: "🧵", color: "#F0F0F0" },
  "minecraft:feather": { name: "Feather", emoji: "🪶", color: "#F0F0F0" },
  "minecraft:gunpowder": { name: "Gunpowder", emoji: "💣", color: "#555555" },
  "minecraft:bone": { name: "Bone", emoji: "🦴", color: "#F5F5F5" },
  "minecraft:bone_meal": { name: "Bone Meal", emoji: "🌱", color: "#F5F5F5" },
  "minecraft:egg": { name: "Egg", emoji: "🥚", color: "#F5F5DC" },
  "minecraft:snowball": { name: "Snowball", emoji: "❄️", color: "#FFFFFF" },
  "minecraft:slimeball": { name: "Slimeball", emoji: "🟢", color: "#55AA22" },
  "minecraft:blaze_powder": { name: "Blaze Powder", emoji: "🔥", color: "#FFAA00" },
  "minecraft:magma_cream": { name: "Magma Cream", emoji: "🔴", color: "#CC2200" },
  "minecraft:ghast_tear": { name: "Ghast Tear", emoji: "💧", color: "#AAFFFF" },
  "minecraft:fermented_spider_eye": { name: "Fermented Spider Eye", emoji: "🕷️", color: "#552222" },
  "minecraft:spider_eye": { name: "Spider Eye", emoji: "🕷️", color: "#772222" },
  "minecraft:rotten_flesh": { name: "Rotten Flesh", emoji: "🍖", color: "#664422" },
  "minecraft:sugar": { name: "Sugar", emoji: "🍬", color: "#FFFFFF" },
  "minecraft:glass_bottle": { name: "Glass Bottle", emoji: "🫙", color: "#A8D8EA" },
  "minecraft:nether_wart": { name: "Nether Wart", emoji: "🍄", color: "#CC2222" },
  "minecraft:ink_sac": { name: "Ink Sac", emoji: "⬛", color: "#111111" },
  "minecraft:experience_bottle": { name: "Bottle o' Enchanting", emoji: "🟢", color: "#00CC00" },
  "minecraft:fire_charge": { name: "Fire Charge", emoji: "🔥", color: "#FF4400" },
  "minecraft:glistering_melon_slice": { name: "Glistering Melon", emoji: "🍉", color: "#FAEE4D" },
  "minecraft:prismarine_crystals": { name: "Prismarine Crystals", emoji: "💎", color: "#55EE88" },
  "minecraft:end_crystal": { name: "End Crystal", emoji: "💠", color: "#FF88FF" },
  "minecraft:chorus_fruit": { name: "Chorus Fruit", emoji: "🔮", color: "#884488" },
  "minecraft:phantom_membrane": { name: "Phantom Membrane", emoji: "👻", color: "#9B8020" },
  "minecraft:nautilius_shell": { name: "Nautilus Shell", emoji: "🐚", color: "#E8D4A0" },
  "minecraft:nautilus_shell": { name: "Nautilus Shell", emoji: "🐚", color: "#E8D4A0" },
  "minecraft:heart_of_the_sea": { name: "Heart of the Sea", emoji: "💙", color: "#0088FF" },
  "minecraft:turtle_helmet": { name: "Turtle Helmet", emoji: "🐢", color: "#5A9E5A" },
  "minecraft:scute": { name: "Scute", emoji: "🐢", color: "#5A9E5A" },
};

export function getItemInfo(id: string): { name: string; emoji: string; color?: string } {
  const clean = id.startsWith("minecraft:") ? id : `minecraft:${id}`;
  return (
    ITEM_NAMES[clean] ?? {
      name: id
        .replace(/^minecraft:/, "")
        .replace(/_/g, " ")
        .replace(/\b\w/g, (c) => c.toUpperCase()),
      emoji: "📦",
      color: undefined,
    }
  );
}

export const DIMENSION_NAMES: Record<string | number, string> = {
  0: "Overworld",
  "-1": "Nether",
  1: "The End",
  "minecraft:overworld": "Overworld",
  "minecraft:the_nether": "Nether",
  "minecraft:the_end": "The End",
};

export const GAME_MODES: Record<number, string> = {
  0: "Survival",
  1: "Creative",
  2: "Adventure",
  3: "Spectator",
};

export const ARMOR_SLOTS: Record<number, string> = {
  103: "Helmet",
  102: "Chestplate",
  101: "Leggings",
  100: "Boots",
};
